version: "3"

services:
  tez-capital:
    container_name: tez-capital-dev
    build:
      context: .
      dockerfile: tez-capital.dockerfile
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik-public
      - traefik.backend=tez-capital-ui
      - traefik.frontend.rule=Host:tez-capital.web.local
      - traefik.port=80
    ports:
      - 8983:80
      - 5173:5173
    volumes:
      - ${PWD}/www:/var/www/html:z
      - ${PWD}/composer.phar:/usr/local/bin/composer
      - node_modules:/var/www/html/node_modules
    networks:
      - traefik-public
      - postgres-network
      - default
    restart: always
    environment:
      - NODE_ENV=development

volumes:
  node_modules:

networks:
  traefik-public:
    external: true
  postgres-network:
    external: true
    name: pgsql_postgres-network
  default:
    driver: bridge